# Generated by Django 6.1 on 2026-08-20 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('tipo_espacio', models.CharField(choices=[('HABITACION', 'Habitación'), ('DEPARTAMENTO', 'Departamento'), ('CASA', 'Casa')], max_length=20)),
                ('precio_alquiler', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='alquiler mensual (Bs)')),
                ('incluye_agua', models.BooleanField(default=False, verbose_name='incluye agua')),
                ('incluye_luz', models.BooleanField(default=False, verbose_name='incluye luz')),
                ('incluye_internet', models.BooleanField(default=False, verbose_name='incluye internet')),
                ('costo_servicios_estimado', models.DecimalField(decimal_places=2, default=0, help_text='Si algun servicio no esta incluido, cuanto paga aparte el inquilino.', max_digits=8, verbose_name='costo estimado de los servicios NO incluidos (Bs)')),
                ('acepta_mascotas', models.BooleanField(verbose_name='acepta mascotas')),
                ('restricciones', models.TextField(blank=True, help_text='Ej.: "solo señoritas". Se muestra antes del primer contacto.')),
                ('lat', models.FloatField(verbose_name='latitud')),
                ('lng', models.FloatField(verbose_name='longitud')),
                ('direccion_referencia', models.CharField(blank=True, max_length=200)),
                ('minutos_caminando', models.PositiveIntegerField(editable=False, help_text='Calculado a partir de lat/lng. No se carga a mano.', verbose_name='minutos caminando a la UAGRM')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('ALQUILADO', 'Ya alquilado')], default='DISPONIBLE', max_length=20)),
                ('publicado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('alquilado_en', models.DateTimeField(blank=True, editable=False, null=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'anuncio',
                'verbose_name_plural': 'anuncios',
                'ordering': ['minutos_caminando', 'precio_alquiler'],
            },
        ),
        migrations.CreateModel(
            name='FotoAnuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='anuncios/%Y/%m/')),
                ('fecha_captura', models.DateTimeField(help_text='Momento en que se tomo la foto. Se muestra en el anuncio.')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='anuncios.anuncio')),
            ],
            options={
                'verbose_name': 'foto',
                'verbose_name_plural': 'fotos',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
