# Generated by Django 6.1 on 2026-08-20 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anuncios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condiciones_aceptadas', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('respondida_en', models.DateTimeField(blank=True, editable=False, null=True)),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='anuncios.anuncio')),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'solicitud de visita',
                'verbose_name_plural': 'solicitudes de visita',
                'ordering': ['-creada_en'],
                'constraints': [models.UniqueConstraint(fields=('anuncio', 'inquilino'), name='una_solicitud_por_anuncio_e_inquilino')],
            },
        ),
    ]
