# Generated by Django 6.1 on 2026-09-18 18:33

import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, upload_to=usuarios.models.ruta_foto_perfil),
        ),
    ]
